CC=g++
OPTION=-std=c++11
INLCUDE=../../include/zstd/internal/algorithm/

basic_sequence_modifier_test.o: basic_sequence_modifier_test.cc
	$(CC) $(OPTION) -I $(INLCUDE) basic_sequence_modifier_test.cc -o basic_sequence_modifier_test.o